const { VITE_CURRENCY,
    VITE_ANONYMOUS_CART,
    VITE_ANONYMOUS_WISHLIST,
    VITE_DISCOUNTS,
    VITE_ENABLE_WEBP,
    VITE_SHOP_NAME,
    VITE_SHOW_SELLER,
    VITE_PRICE_ADDITIONAL_TEXT,
    VITE_PRICE_ADDITIONAL_LINK_TEXT, } = import.meta.env

export const SHOP_SETTINGS = {
    ENABLE_WEBP: VITE_ENABLE_WEBP ? (VITE_ENABLE_WEBP === "TRUE" ) : true,
    DISCOUNTS: VITE_DISCOUNTS ? (VITE_DISCOUNTS === "TRUE" ) : true,
    SHOW_SELLER: VITE_SHOW_SELLER ? (VITE_SHOW_SELLER === "TRUE" ) : true,
    CURRENCY: VITE_CURRENCY ? VITE_CURRENCY : "€",
    PRICE_ADDITIONAL_TEXT: VITE_PRICE_ADDITIONAL_TEXT ? VITE_PRICE_ADDITIONAL_TEXT : "Default GTC SHORT TEXT",
    PRICE_ADDITIONAL_LINK_TEXT: VITE_PRICE_ADDITIONAL_LINK_TEXT ? VITE_PRICE_ADDITIONAL_LINK_TEXT : "Default MORE INFO TEXT",
    SHOP_NAME: VITE_SHOP_NAME ? VITE_SHOP_NAME : null,
    ANONYMOUS_CART: VITE_ANONYMOUS_CART ? (VITE_ANONYMOUS_CART === "TRUE" ) : true,
    ANONYMOUS_WISHLIST: VITE_ANONYMOUS_WISHLIST ? (VITE_ANONYMOUS_WISHLIST === "TRUE" ) : true,

}

